import LEFT_BOTTOM_CONTAINER from "./LEFT_BOTTOM_CONTAINER"
import RIGHT_BOTTOM_CONTAINER from "./RIGHT_BOTTOM_CONTAINER"
export default function TOP_DIV(){
    return (<div id="BOTTOM_DIV"><LEFT_BOTTOM_CONTAINER/><RIGHT_BOTTOM_CONTAINER/></div>);
}